spring:
  application:
    name: merge_xml
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yaml
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: always

merge-xml:
  config-path: ${MERGE_XML_CONFIG_PATH:config.txt}

springdoc:
  swagger-ui:
    path: /swagger
  override-with-generic-response: false

openapi:
  title: @project.name@
  version: @project.version@
  description: @project.description@